# Generated by Django 3.2.12 on 2025-09-03 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cca2', models.CharField(help_text='Código de 2 letras do país', max_length=2, unique=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('subregion', models.CharField(blank=True, max_length=100, null=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.PositiveIntegerField()),
                ('flag_url', models.URLField(max_length=255)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do Roteiro', max_length=200)),
                ('start_date', models.DateField(help_text='Data de início da viagem')),
                ('departure_date', models.DateField(help_text='Data de partida da viagem')),
                ('description', models.TextField(help_text='Descrição detalhada do roteiro')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Preço do roteiro (opcional)', max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, help_text='Imagem de destaque do roteiro', null=True, upload_to='itinerary_images/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='catalogo.country')),
            ],
            options={
                'verbose_name': 'Roteiro',
                'verbose_name_plural': 'Roteiros',
                'ordering': ['start_date'],
            },
        ),
    ]
