# Generated by Django 3.2.12 on 2025-09-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Pais',
        ),
    ]
