# Generated by Django 3.2.12 on 2025-09-03 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_rename_country_pais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['data_inicio'], 'verbose_name': 'Roteiro', 'verbose_name_plural': 'Roteiros'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['nome'], 'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.RenameField(
            model_name='itinerary',
            old_name='start_date',
            new_name='data_inicio',
        ),
        migrations.RenameField(
            model_name='itinerary',
            old_name='departure_date',
            new_name='data_partida',
        ),
        migrations.RenameField(
            model_name='itinerary',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='itinerary',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='population',
            new_name='populacao',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='region',
            new_name='regiao',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='subregion',
            new_name='subregiao',
        ),
    ]
